# ---------------- #
#   Main Configs   #
# ---------------- #
# Permalinks
permalink:        pretty
port:    4008
# Setup
url:              https://mda07022.github.io
# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''
title:            Levy's Blog
# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:     '我的新博客在github安家了'
# The tags listed as entries in the sidebar
sidebar_tags:     [Java, js, fore, sql]
# Fallback image and color if not overwritten for tag or post
image:            
color:            '#268bd2'


# ---------------- #
#      Author      #
# ---------------- #
author:
  name:           'linwei'
  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        mda07022
  github:         mda07022
  
  # Setting a disqus username will enable the comment section
  disqus:         mda07022
  # This photo will be used in the about section
  photo:    /public/img/photo.jpg      
  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  #about:          |
    

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/